### ISSUE TITLE
Error with AVP and appliedenergistigs 2

### ISSUE THREAD

**Issue by Bastelking** [Ri5ux/AliensVsPredator#46] opened 2021-02-15 17:15 UTC
AVP and applieenergistigs are not compatible at same time, because if i have both installed the game crashes due to an Server error, it sais Dimensin 3 could not be loadet, because it already exists. Please fix

**Comment by Rumcajz23th** [comment] 2021-03-08 12:08
Hello, everything what you need to do is, that you go to config and change the dimension of the applied energistics... go to: "Your minecraft destination\config\AppliedEnergistics2" there is config with name AppliedEnergistics2.cfg there look for: I:storageDimensionID=3 and change the 3 for ID which is available for you. in my case that was 20 so it will look like this:
I:storageDimensionID=20 Then save the config and you can load your minecraft.... 
Downsite of this is, if you already visit the spatial storage dimension... then you will no longer be able to visit that dimension because applied energistics will have the dimension on ID 20 instead of the old 3... so for your safety make sure that you remove all the things and yourself from the dimension then make backup and after that make changes...

**Comment by bvanseg** [comment] 2023-03-19 04:35
This appears to be a duplicate of #40, which requests the ability to change dimension IDs. The ability to change dimension IDs via config file is planned in #142. Closing.

**Closed by bvanseg** 2023-03-19 04:35 UTC
Labels: duplicate
