### ISSUE TITLE
Modpack crashes with aliensvspredator-7.0.0.72.

### ISSUE THREAD

**Issue by Njet75** [Ri5ux/AliensVsPredator#283] opened 2023-04-14 16:24 UTC
Latest Crash aliensvspredator-7.0.0.72. crashes in my modpack but work fine by its own.
Whats causing this crash?

/Michael 
[crash-2023-04-14_18.20.52-client.txt](https://github.com/Ri5ux/AliensVsPredator/files/11234993/crash-2023-04-14_18.20.52-client.txt)

**Comment by bvanseg** [comment] 2023-04-14 17:02
This crash is caused by aliens being given their own custom spawn type to separate their spawn cap from vanilla mobs. It works fine on its own, but some mods cause this custom creature type to crash the game, for reasons I'm not yet aware of. I suspect it's due to mod load order, but not sure.

You can temporarily fix this by going into your config (config/avp/config.json) and setting `customCreatureTypesEnabled` to `false`.

Also if you'd like to help debug this issue to work with your modpack specifically, please reach out to me on Discord: Boston#8570

**Comment by bvanseg** [comment] 2023-04-14 18:14
Update: may be resolved by #286, but needs testing with the modpack in your report to be sure @Njet75.

**Comment by bvanseg** [comment] 2023-04-14 19:10
#286 appears to have fixed the issue. Closing.

**Closed by bvanseg** 2023-04-14 19:10 UTC
Labels: bug
