### ISSUE TITLE
Crash when looking at blastdoor with Waila installed

### ISSUE THREAD

**Issue by MetaverseRPN** [Ri5ux/AliensVsPredator#18] opened 2019-07-11 04:47 UTC
Hey,
I and a few other players on my server are crashing when looking at Blastdoor and got this crashlog:
https://gist.github.com/nacjm/2a01b4956a72f623e2b19d188cbf550b

any ideas why this is happening?

Thanks,
----
NN

**Comment by Njet75** [comment] 2023-03-17 23:27
This also happens to me.Only solution to use mcedit and remove door.

**Comment by bvanseg** [comment] 2023-03-19 04:21
Will look into this.

**Comment by bvanseg** [comment] 2023-03-19 20:24
Unable to reproduce this in 1.12.2. If this issue is for an older version of AvP on an older MC version, those versions are no longer supported. If you still encounter this issue in 1.12.2 latest, please feel free to make another issue. Closing.

**Closed** 2023-03-19 20:24 UTC
Labels: bug
